Repository buddypress/BP-REST, pull requests merged in 2019-02, with the labels that each got.

#141 Schema and Collections Review
  README.md
  bp-rest.php
  includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
  includes/bp-components/classes/class-bp-rest-components-endpoint.php
  includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php
  includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
  includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
  includes/bp-members/classes/class-bp-rest-members-endpoint.php
  includes/bp-messages/classes/class-bp-rest-messages-endpoint.php
  includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php
  includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
  includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
  includes/bp-xprofile/classes/class-bp-rest-xprofile-groups-endpoint.php
  includes/functions.php
  tests/activity/test-controller.php
  tests/groups/test-controller.php
  tests/notifications/test-controller.php
  tests/xprofile/test-group-controller.php
Labels: enhancement

#143 Make sure xProfile component is active before using it
  includes/bp-members/classes/class-bp-rest-members-endpoint.php
Labels: Component: Members, bug

#146 WIP - BP_User_Query support to the Members endpoint
  bp-rest.php
  includes/bp-members/bp-members-filters.php
  includes/bp-members/classes/class-bp-rest-members-endpoint.php
  tests/members/test-controller.php
Labels: Component: Members, enhancement

#147 Unit tests coverage review
  .travis.yml
  includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
  includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php
  includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
  includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
  includes/bp-members/classes/class-bp-rest-members-endpoint.php
  includes/bp-messages/classes/class-bp-rest-messages-endpoint.php
  includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php
  includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
  includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
  includes/bp-xprofile/classes/class-bp-rest-xprofile-groups-endpoint.php
  includes/functions.php
  tests/activity/test-controller.php
  tests/components/test-controller.php
  tests/groups/test-controller.php
  tests/groups/test-group-invites-controller.php
  tests/groups/test-group-membership-controller.php
  tests/members/test-controller.php
  tests/notifications/test-controller.php
  tests/xprofile/test-data-controller.php
  tests/xprofile/test-field-controller.php
  tests/xprofile/test-group-controller.php
Labels: enhancement

#160 Test BuddyPress Versions
  .travis.yml
  README.md
Labels: enhancement

#159 Endpoints Permissions Check Override
  bp-rest.php
  includes/bp-activity/classes/class-bp-rest-activity-endpoint.php
  includes/bp-components/classes/class-bp-rest-components-endpoint.php
  includes/bp-groups/classes/class-bp-rest-group-invites-endpoint.php
  includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
  includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
  includes/bp-members/classes/class-bp-rest-members-endpoint.php
  includes/bp-messages/classes/class-bp-rest-messages-endpoint.php
  includes/bp-notifications/classes/class-bp-rest-notifications-endpoint.php
  includes/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
  includes/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php
  includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
  tests/xprofile/test-group-controller.php
Labels: enhancement
